/* eslint-disable */
/* tslint:disable */
import {ImageURISource} from "react-native";

/**
 * This file is auto-generated by react-native-image-resource-generator
 * !!! DO NOT EDIT !!!
 * For more information check the documentation:
 * https://github.com/svbutko/react-native-image-resource-generator
*/

export class OnboardingResources {
  static readonly onboarding_background_1: ImageURISource = require("../../../../market/resources/images/onboarding/onboarding_background_1.png");
  static readonly onboarding_background_2: ImageURISource = require("../../../../market/resources/images/onboarding/onboarding_background_2.png");
  static readonly onboarding_background_3: ImageURISource = require("../../../../market/resources/images/onboarding/onboarding_background_3.png");
  static readonly onboarding_background_4: ImageURISource = require("../../../../market/resources/images/onboarding/onboarding_background_4.png");
}

export class TabbarDarkResources {
  static readonly bag: ImageURISource = require("../../../../market/resources/images/tabbarDark/bag.png");
  static readonly date: ImageURISource = require("../../../../market/resources/images/tabbarDark/date.png");
  static readonly home: ImageURISource = require("../../../../market/resources/images/tabbarDark/home.png");
  static readonly menu: ImageURISource = require("../../../../market/resources/images/tabbarDark/menu.png");
  static readonly news: ImageURISource = require("../../../../market/resources/images/tabbarDark/news.png");
}

export class TabbarInactiveResources {
  static readonly bag: ImageURISource = require("../../../../market/resources/images/tabbarInactive/bag.png");
  static readonly date: ImageURISource = require("../../../../market/resources/images/tabbarInactive/date.png");
  static readonly home: ImageURISource = require("../../../../market/resources/images/tabbarInactive/home.png");
  static readonly menu: ImageURISource = require("../../../../market/resources/images/tabbarInactive/menu.png");
  static readonly news: ImageURISource = require("../../../../market/resources/images/tabbarInactive/news.png");
}

export class TabbarLightResources {
  static readonly bag: ImageURISource = require("../../../../market/resources/images/tabbarLight/bag.png");
  static readonly date: ImageURISource = require("../../../../market/resources/images/tabbarLight/date.png");
  static readonly home: ImageURISource = require("../../../../market/resources/images/tabbarLight/home.png");
  static readonly menu: ImageURISource = require("../../../../market/resources/images/tabbarLight/menu.png");
  static readonly news: ImageURISource = require("../../../../market/resources/images/tabbarLight/news.png");
}

export class ImageResources {
  static readonly arrow_down: ImageURISource = require("../../../../market/resources/images/arrow_down.png");
  static readonly arrow_left: ImageURISource = require("../../../../market/resources/images/arrow_left.png");
  static readonly arrow_right: ImageURISource = require("../../../../market/resources/images/arrow_right.png");
  static readonly avatar: ImageURISource = require("../../../../market/resources/images/avatar.png");
  static readonly calendarblank: ImageURISource = require("../../../../market/resources/images/CalendarBlank.png");
  static readonly camera: ImageURISource = require("../../../../market/resources/images/camera.png");
  static readonly check: ImageURISource = require("../../../../market/resources/images/check.png");
  static readonly close_modal: ImageURISource = require("../../../../market/resources/images/close_modal.png");
  static readonly drop_down: ImageURISource = require("../../../../market/resources/images/drop_down.png");
  static readonly eye: ImageURISource = require("../../../../market/resources/images/Eye.png");
  static readonly eyeclosed: ImageURISource = require("../../../../market/resources/images/EyeClosed.png");
  static readonly menu: ImageURISource = require("../../../../market/resources/images/menu.png");
}
